# Generated by Django 4.2.5 on 2023-09-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("install_ts", models.DateTimeField(auto_now_add=True)),
                ("update_ts", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("aadhar_card_no", models.CharField(max_length=12, null=True)),
                ("phone", models.CharField(max_length=10)),
                ("email_id", models.EmailField(max_length=254, null=True)),
                ("expected_date_of_joining", models.DateField(null=True)),
            ],
            options={
                "db_table": "user_detail",
            },
        ),
    ]
